apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pruebaMySql
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        k8s-app: pruebaMySql
    spec:
      containers:
      - name: pruebaMySql
        image: phpmyadmin/phpmydamin
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: pruebaMySql
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    k8s-app: pruebaMySql
