apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: myadmin
  name: pruebamysql
  namespace: aksbabel
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: myadmin
    spec:
      containers:
      - image: phpmyadmin/phpmyadmin
        imagePullPolicy: Always
        name: pruebamysql
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
          - name: PMA_ARBITRARY
            value: '1'
