apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pruebasite
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        k8s-app: pruebasite
    spec:
      containers:
      - name: pruebasite
        image: acrkeyronbabel.azurecr.io/pruebasite:$(Build.BuildNumber)
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
